# docker service rm ocelot_bakery_ui || true && docker stack deploy -c $(pwd)/ui.yaml --resolve-image=never ocelot_bakery

version: '3.7'

services:

  ui:
    image: lanl0rd/js
    networks:
      - network_overlay
    volumes:
      - ../../../:/app
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    working_dir: /app
    ports:
      - "4200"
    command: nx serve bakery --host 0.0.0.0 --disableHostCheck

networks:
  network_overlay:
    external: true