echo "APT"
echo "..."

sudo apt update
sudo apt install -y \
    curl \
    wget \
    git \
    zip \
    unzip \
    mergerfs \
    sshfs \
    rsync \
    openssh-client \
    openssh-server \
    openssl \
    dnsutils \ 
    udftools \
    sshpass \
    exfat-utils \
    exfat-fuse \
    f2fs-tools \
    xfsprogs \
    btrfs-progs \
    net-tools \
    zfsutils-linux \
    quota \
    nfs-kernel-server \
    zsh \
    ksh \
    gcc \
    g++ \
    make \
    python3-pip \
    build-essential \
    chromium-browser \
    locales \
    vim \
    apt-transport-https \
    ca-certificates \
    gnupg-agent \
    software-properties-common \
    gdebi \
    x11vnc \
    sysstat \
    libtool \
    autoconf \
    automake \
    linux-headers-generic \
    dconf-editor \
    gnome-tweak-tool \
    gnome-shell-extensions \
    latte-dock \