services:
  frpc:
    image: snowdreamtech/frpc
    restart: always
    network_mode: host
    volumes:
        - '../frp/frpc.ini:/etc/frp/frpc.ini'
        # - '/var/run/docker.sock:/tmp/docker.sock:ro'
    logging:
      options:
        max-size: 1g
    environment:
      - FRP_SERVER_ADDR=x.x.x.x
      - FRP_SERVER_PORT=7000
      - SSH_REMOTE_PORT=2222
    

