services:
  frps:
    image: snowdreamtech/frps
    restart: always
    network_mode: host
    volumes:
        - '../frp/frps.ini:/etc/frp/frps.ini'
    logging:
      options:
        max-size: 1g
    environment:
      - FRP_SERVER_PORT=7000
    
