version: '3.3'

services:
  guacamole:
    image: lan10rd/guacamole
    restart: always
    restart-policy: 
      condition: on-failure
    network_mode: host
    networks:
      - host
    volumes:
        - ../guacamole/config:/config
    logging:
      options:
        max-size: 1g
    ports:
      - 8080
    
networks:
  host:
    name: host
    external: true
