version: '3.3'

services:
  guacamole:
    image: 'jc21/nginx-proxy-manager'
    restart: always
    restart-policy: 
      condition: on-failure
    network_mode: host
    networks:
      - host
    logging:
      options:
        max-size: 1g
    volumes:
      - ../nginx-proxy-manager/data:/data
      - ../nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    
networks:
  host:
    name: host
    external: true
