rate: '60 * 60 * 10 * 1000'

primary:
  src:
    type: 'remote'
    path: ''
  dst: 
    type: 'local'
    path: ''

secondary:
  - src:
      type: 'local'
      path: ''
    dst:
      type: 'local'
      path: ''