

services:
  guacamole:
    image: lan10rd/guacamole
    volumes:
      - $HOME/lan10rd/setup/docker/guacamole/config:/config
    ports:
      - 8080:8080

# volumes:
#   postgres:
#     driver: local