# docker service rm ocelot_dev_face || true && docker stack deploy -c $(pwd)/face.yaml --resolve-image=never ocelot_dev

version: '3.7'

services:

  face:
    image: lanl0rd/face
    environment:
      - HTTP_PASSWORD=$HTTP_PASSWORD
    networks:
      - network_overlay
    ports:
      - "80"
      - "5090"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.ocelot_dev_face.rule=Host(`face.ocelot.work`)
        - traefik.http.services.ocelot_dev_face.loadbalancer.server.port=80
        - traefik.http.services.ocelot_dev_face.loadbalancer.sticky.cookie.name=sticky
        - traefik.http.services.ocelot_dev_face.loadbalancer.sticky.cookie.secure=true
        - traefik.http.services.ocelot_dev_face.loadbalancer.sticky.cookie.httpOnly=true
    volumes:
      - ../../../:/root/ocelot
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  network_overlay:
    external: true