version: '3.3'

services:

  guacamole:
    image: oznu/guacamole
    volumes:
        - ./guacamole/config:/config
    logging:
      options:
        max-size: 1g
    restart: always
    ports: 
      - '8080:8080'
    # first time login is guacadmin / guacadmin

  frpc:
    image: snowdreamtech/frpc
    logging:
      options:
        max-size: 1g
    restart: always
    network_mode: host
    volumes:
        - './frp/frpc.ini:/etc/frp/frpc.ini'
    environment:
      - FRP_SERVER_ADDR=x.x.x.x
      - FRP_SERVER_PORT=7000
      - SSH_REMOTE_PORT=2222

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager'
    logging:
      options:
        max-size: 1g
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    ports: 
      - '80:80'
      - '80:80/udp'
      - '443:443'
      - '443:443/udp'
      - '81:81'
    restart: always
    # first time login is admin@example.com / changeme