# docker stack deploy --prune -c frpc.yaml lan10rd

version: '3.3'

services:

    frpc:
        restart: always
        network_mode: host
        volumes:
            - ./frpc.ini:/etc/frp/frpc.ini
        environment:
            - FRP_SERVER_ADDR=x.x.x.x
            - FRP_SERVER_PORT=7000
        image: snowdreamtech/frpc